export const ErrorMessage:any = {
    SOMETHING_WENT_WRONG: 'Something went wrong. Please try again after sometime',
    INVALID_ACCESS: "You are not allowed to access the resource",
    BODY_NOT_SENT: "Request body cannot be empty",
    EMPTY_BODY: "Request body cannot be empty",
    UNAUTHORIZED: "You are not authorized to perform the operation",
    INVALID_PURPOSE: "Invalid parameters defined during file upload",
    INSUFFICIENT_SCOPE: "You don't have sufficient permissions to perform this operation",
    REQUIRED_PARAMETERS: "Request body received with incorrect parameters",
    NOT_AUTHORIZED: "You are not authorized to perform the operation",
    INVALID_IMAGE_FORMAT: "This image format is not supported",
    INVALID_ORGANIZATION_TYPE: "Invalid organization type received in the request",
    INVALID_DATE: "Invalid date received in the request",

    INVALID_ORGANIZATION: "You don't have sufficient permissions to access the organization",
    ORGANIZATION_NOT_FOUND: "No such organization exist. Contact your system administrator",
    INVALID_CHILD_ORGANIZATION_ACCESS: "You don't have sufficient permissions to access the organization",
    SUB_ORGANIZATION_PRESENT: "There are sub organization(s) associated with this organization which must be removed prior to deleting the organization",
    INVALID_ORGANIZATION_CREATE: "You don't have sufficient permissions to create the organization",
    ORGANIZATION_NAME_VALID: "Organization name can only contains alpha-numeric characters",
    PARENT_ORGANIZATION_NOT_FOUND: "No such parent organization exist. Contact your system administrator",
    ORGANIZATION_DETAILS_NOT_FOUND: "No such organization details exist. Contact your system administrator",
    SELF_ORGANIZATION_DELETE: "Cannot delete organization by itself",
    SELF_ORGANIZATION_MARKET_PLACE: "Cannot modify market place by itself",

    MAXIMUM_ORGANIZATION_LEVEL: "Maximum 4 level sub-organization(s) can be configured!",
    MULTI_ORG_HIERARCHY: "Identity already has hierarchy level access",
    IDENTITY_NOT_FOUND: "No such Identity found in the organization",
    INVALID_PHONENUMBER: "Phone number is not valid",
    MINIMUM_NAME_VALID: "Name should be minimum 3 characters long and only contains alpha-numeric characters",
    USER_NAME_VALID: "Name can only contains alpha-numeric characters",
    INVALID_ACCESS_IDENTITY: "You don't have sufficient permissions to create the identity",
    INVALID_EMAIL: "Email address is not valid",
    INVALID_ROLE: "Invalid role assigned to the user",
    INVALID_ROLE_TYPE: "Invalid role received in the request",
    ROLE_EXIST: "Role already exists in the system",
    PERMISSION_EXIST: "Permission already exists in the system",
    IDENTITY_FOUND: "Identity already exists in the system",
    INVITE_NOT_FOUND: "No invitation exist in the system",
    INVALID_RESENT_INVITE: "You don't have sufficient permissions to resend the invitation",
    INVITE_NOT_SENT_UNSUBSCRIBED: "Invitation not sent. Identity has unsubscribed from the shasta email list.",
    IDENTITY_DETAILS_NOT_FOUND: "No such identity details exist. Contact your system administrator",
    INVALID_PASSWORD: "The password you entered is incorrect",
    PASSWORD_REQUIREMENT: "The password must be at least 8 characters long and contain one uppercase letter, one lowercase letter and one special character.",
    INVALID_ID: "UserId is invalid",
    INVALID_IDENTITY: "No such Identity exists. Contact your system administrator",
    CANNOT_BLOCK_ITSELF: "Cannot block Identity by itself",
    CANNOT_DELETE_ITSELF: "Cannot delete Identity by itself",
    IDENTITY_ALREADY_UNSUBSCRIBED: "Identity has already unsubscribed to get the organization updates",
    IDENTITY_ALREADY_SUBSCRIBED: "Identity has already subscribed to get the updates",
    INVITE_NOT_DELETE: "You are not allowed to delete the Invite",

    PERMISSION_NOT_FOUND: "No such permission exist. Contact your system administrator",
    INVALID_PERMISSION: "Invalid permission received in the request",
    ROLE_NOT_FOUND: "No such role exist. Contact your system administrator",
    SYSTEM_ROLE_CANNOT_UPDATE: "System role cannot be updated",
    INVALID_SYSTEM_ROLE_ACCESS: "You don't have sufficient permissions to modify system role",
    CANNOT_INVITE_ITSELF: "Cannot invite Identity by itself",
    CANNOT_UPDATE_ROLE_ITSELF: "Cannot update role by itself",
    CANNOT_ASSIGNED_VENUE_ITSELF: "Cannot assign venue by itself",
    CANNOT_ASSIGNED_VENUE_PERMISSION_TO_ADMIN: "Cannot assign venue level permission to an Admin",

    INVALID_PADMIN: 'Identity exist in other organization with different role, hence cannot be added as Platform-Admin.',
    IDENTITY_ALREADY_PADMIN: 'Identity with Platform-Admin permission cannot be added to other organization with different role.',
    IDENTITY_HIERARCHY: 'Identity can be part of same organization hierarchy only and not outside of the hierarchy.',
    IDENTITY_DELETE: 'Removing identity from this organization, violate same organization hierarchy concept.',
    
    INVALID_CREDENTIAL: "Wrong email or password",

    LINK_EXPIRED: "Reset password link has expired.",

    MAXIMUM_EMAIL_LIMIT: "You have reached the maximum limit for reset password. Please check your mailbox or contact Shasta support",
    
    INFRASTRUCTURE_EXISTS: "Infrastructure is already attached to the other Venue",
    INFRASTRUCTURE_NOT_FOUND: "Infrastructure not exists in the system",
    INFRATYPE_NOT_FOUND: "Infratype not exists in the system",
    INFRATYPE_EXISTS: "Infratype already exists in the system",
    INVALID_SERIALNUMBER: "Invalid serial number. A serial number should only be 12 HEX characters (a-f, 0-9)",
    INFRASTRUCTURE_NOT_FOUND_TIP: "Unable to add Infrastructure at this moment. Please try again after sometime",
    INFRASTRUCTURE_UNASSIGNED: "Infrastructure is not assigned to any venue",
    INFRASTRUCTURE_DETAILS_NOT_SENT: "Required infrastructure details are not specified properly",

    VENUE_NOT_FOUND: "No such Venue exists. Contact your system administrator",
    MAXIMUM_VENUE_LEVEL: "Maximum 4 level sub-venue(s) can be configured!",
    VENUE_DETAILS_NOT_FOUND: "Missing venue details in the request",
    DEFAULT_VENUE_UPDATE: "Default venue cannot be updated",
    DEFAULT_VENUE_DELETE: "Default venue cannot be deleted",
    FLOOR_PLAN_NOT_FOUND: "No Floor plan found for this venue",
    CHILD_VENUE_EXISTS: "There are sub venue(s) associated with this venue which must be removed prior to deleting the venue",
    INVALID_FLOOR_DATA: "Invalid Floor plan data",
    FLOOR_EXISTS: "Floor with this name already exists in the venue",
    TOP_LEVEL_MUST_BE_SITE: "Top level venue must be site only",
    INVALID_VENUE_TYPE: "Child venue of this type cannot be created for the given parent venue",
    PARENT_VENUE_NOT_FOUND: "No such parent venue exist. Contact your system administrator",
    VENUE_NOT_BELONGS_TO_ORG: "Parent venue does not belong to given organization",
    VENUE_INVALID_ACCESS: "Invalid venues received in the request",
    VENUE_INVALID_ASSIGNMENT: "Invalid assignment of venue to Identity",
    REASON_NOT_SENT: "Reason not sent in the request",
    INVALID_STATE: "Invalid state received in the request",
    CUSTOM_VENUE_CREATION: "You don't have sufficient permissions to create new venue as you have only some set of venue access",
    
    SSID_NOT_MATCH: "Network Name and SSID doesn't match",
    NETWORKTYPE_NOT_FOUND: "No such Network Type exists.",
    NETWORK_NOT_FOUND: "No such network exists. Contact your system administrator",
    NETWORK_EXISTS: "Network with same SSID already exists in the system",
    RADIUS_REQUIRED: "Enter the Radius server details",
    RADIUS_NOT_REQUIRED: "Missing radius server required for this network type",
    INVALID_RADIUS_HOST: "Invalid radius host IP address found",
    PASSWORD_NOT_REQUIRED: "No Password required for this network type",
    PASSWORD_REQUIRED: "Missing Password for this network type",
    AUTHORIZATION_PORT_REQUIRED: "Set the Authorization Port",
    ACCOUNTING_PORT_REQUIRED: "Set the Accounting Port",
    RADIUS_SECRET_REQUIRED: "Missing password for the radius secret",
    COA_CONFIG_REQUIRED: "COA configurations are missing",
    VENUE_REMOVE_NETWORK: "Venue already removed from the network",
    VENUE_ATTACH_NETWORK: "Venue already attached to the network",
    AP_NOT_FOUND: "No such AP Profile exists. Contact your system administrator",
    RF_NOT_FOUND: "No such RF Profile exists. Contact your system administrator",
    DUPLICATE_BANDS: "Duplicate bands are not allowed",
    DEFAULT_PROFILE_CANNOT_DELETE: "Default profile cannot be deleted",

    TIP_AUTH_DOWN: "Unable to process your request at this time. Please try again after sometime",
    AUTH0_DOWN: "Unable to process your request at this time. Please try again after sometime",
    TIP_PROV_DOWN: "Unable to process your request at this time. Please try again after sometime",
    TIP_GTW_DOWN: "Unable to process your request at this time. Please try again after sometime",
    ORG_DOWN: "Unable to process your request at this time. Please try again after sometime",
    DB_DOWN: "Unable to process your request at this time. Please try again after sometime"
};